name: Robot test

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v2
      - uses: nanasess/setup-chromedriver@master
      - name: Build using python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install dependencies [pip]
        run: |
          python -m pip install pip --upgrade pip
          pip install robotframework
          pip install robotframework-selenium2library
          sudo apt-get update
          sudo apt-get --only-upgrade install google-chrome-stable
          google-chrome --version
          chromedriver --version
          
      - name: Run Robot Tests
        run: |
          robot -d rep -i OptimyLoginPageComprehensiveTest .
          echo /home/runner/work/robots-actions/robots-actions/rep/log.html


# name: Robot Framework

# on:
#   push:
#     branches: [ master ]
# jobs:
#     test:
#         runs-on: ubuntu-latest
#         steps:
#         - uses: actions/checkout@v2
#         - name: Execute tests
#           uses: joonvena/robotframework-docker-action@v0.1
#           env:
#             BROWSER: chrome
#             ROBOT_TESTS_DIR: ${{ github.workspace }}/vincentjohnroa/dummy
